services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - redis

  test:
    build: .
    command: bash -c "bundle exec rails db:test:prepare && bundle exec rspec"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      RAILS_ENV: test
      REDIS_URL: redis://redis:6379/1
      RAILS_MAX_THREADS: 1
      DISABLE_SPRING: 1
    depends_on:
      - redis

volumes:
  redis_data:
  bundle_cache:
  node_modules: 